name: Deploy docs app to production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}
  SHELL: bash
  PNPM_HOME: /home/runner/.local/share/pnpm
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/apps/docs/**
      - src/packages/**
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      
      - name: Install pnpm
        run: npm i pnpm -g

      - name: Setup pnpm
        shell: bash
        run: pnpm setup

      - name: Setup pnpm variables
        run: source /home/runner/.bashrc

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}